#!/bin/sh
set -e
set -x

dl() {
  curl -s -k -L "${2}" -o "${1}"
}

dl_bin() {
  local dest="${HOME}/.bin/${1}"
  dl "${dest}" "${2}"
  chmod 775 "${dest}"
}

dl_completion() {
  dl "completion.d/${1}" "${2}"
}

cp $GOROOT/misc/bash/go completion.d/go
dl_completion "nvm" "https://raw.github.com/creationix/nvm/master/bash_completion"
dl_completion "lein" "https://raw.github.com/technomancy/leiningen/master/bash_completion.bash"
dl_completion "android" "https://raw.github.com/mbrubeck/android-completion/master/android"
dl_completion "git" "https://raw.github.com/git/git/master/contrib/completion/git-completion.bash"
dl_completion "ipython" "https://raw.github.com/ipython/ipython/master/examples/core/ipython-completion.bash"
dl_completion "maven" "https://raw.github.com/juven/maven-bash-completion/master/bash_completion.bash"

dl_bin "git-imerge" "https://raw.github.com/mhagger/git-imerge/master/git-imerge"
dl_bin "ghi" "https://raw.github.com/stephencelis/ghi/master/ghi"
dl_bin "vcprompt" "https://raw.github.com/djl/vcprompt/master/bin/vcprompt"
dl_bin "svtget" "https://raw.github.com/mmn/svtget/master/bash/svtget"

npm install -g bower
bower completion > completion.d/bower

curl -s -k -L "https://raw.github.com/rupa/z/master/z.sh" -o z

youtube-dl -U

(
  cd ~/repos/github/hub
  git pull origin master
  rake standalone
)

cp ~/repos/github/hub/hub ~/.bin/hub
