#!/bin/bash
#
# Opens editor (usually emacs)
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

set -e

cmd=$(basename ${0})

[ -z ${1} ] \
    && emacsargs="${emacsargs} ."

# if runnung under osx, make some changes
[ "${OSTYPE:0:6}" = "darwin" ] \
    && [ -x "/Applications/Emacs.app/Contents/MacOS/Emacs" ] \
    exec /Applications/Emacs.app/Contents/MacOS/Emacs $emacsargs $*

if [ $(which emacs) ]; then
    if [ -n ${DISPLAY} ] && [ ${cmd} != editor-nobg ]; then
        exec emacs $emacsargs $* &
        exit
    else
        exec emacs $emacsargs $*
    fi
fi

[ $(which vim) ] \
    && exec vim $*

[ $(which vi) ] \
    && exec vi $*

echo "no suitable editor found"
