#!/bin/bash
#

if [ -x ~/.opt/emacs/lib-src/emacsclient ]; then
  emacs=~/.opt/emacs/src/emacs
elif [ -x /usr/bin/emacsclient ]; then
  emacs=/usr/bin/emacsclient
fi

if [ -e ~/.config/darkmode ]; then
  mode=dark
else
  mode=light
fi
export GTK2_RC_FILES=${HOME}/.config-xmonad/gtk/gtk-2.0/${mode}

t=${TERM}
[ "${TERM}" == "rxvt-unicode-256color" ] && t="xterm";
export TERM=${t}
exec ${emacs} "$@"
