#!/bin/sh
#
# Open magit in current directory
#

set -e

VERSION="1"

SUBDIRECTORY_OK=Yes
OPTIONS_KEEPDASHDASH=""
OPTIONS_SPEC="\
git magit [path]"

version_print() {
    echo "git magit version ${VERSION}"
}

emacs --eval "(init-magit-status \"`pwd`\")" 


