#!/bin/bash
#
# Manage directory synchronized repositories repositories stored in a gitolite repository
#
# Author: Thomas Frössman  ( thomasf@jossystem.se / http://thomas.jossystem.se )
# Updates to this file will probably be available at https://github.com/thomasf/dotfiles/
#

#set -x
#set -u

set -e


base="${HOME}/.config/dotfiles/"

# Run dotfiles syncrhonization and/or source INSTALLER script if found
function install_repositories {
    local all=${base}/*
    for d in ${all}; do
        cd ${d}
        [ -e .dotfilesrc ] && dotfiles -s ${force_opt} -R .
        [ -e "INSTALLER" ] && source ./INSTALLER
        true
    done
}

# colors
reset="$(tput sgr0)"
red="$(tput setaf 1)"
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
magenta="$(tput setaf 5)"

# Should installations be forced?
force_opt=""
if [[ ${1} == "-f" ]]; then
    force_opt="-f"
    shift 1
fi

case ${1} in
    # Git add all changes in all repositories
    add)
        for d in ${base}/*; do
            cd ${d}
            git add -A
        done
        ;;
    # Add/commit/pull/push all repositories
    burst)
        for d in ${base}/*; do
            (
                cd ${d}
                n=$(basename ${d})

                status=$green
                o=$(git add -A) || status=$red
                [[ $status == $red ]] && echo "${status}###### ${yelllow}:ADD:${magenta}${n}: ${reset}${o}"

                status=$green
                o=$(git commit -m"*** burst commit ***" ) || status=$red
                if [[ $status == $green ]]; then
                    echo "${status}###### ${yelllow}COMMIT ${magenta}${n}${reset}"
                else
                    echo "${status}###### ${yelllow}COMMIT ${magenta}${n}: ${reset}${o}"
                fi

                status=$green
                o=$(git pull origin master ) || status=$red
                if [[ $status == $green ]]; then
                    echo "${status}###### ${yelllow}PULL ${magenta}${n}${reset}"
                else
                    echo "${status}###### ${yelllow}PULL ${magenta}${n}: ${reset}${o}"
                fi

                status=$green
                o=$(git push --porcelain origin master ) || status=$red
                if [[ $status == $green ]]; then
                    echo "${status}###### ${yelllow}PUSH ${magenta}${n}${reset}"
                else
                    echo "${status}###### ${yelllow}PUSH ${magenta}${n}: ${reset}${o}"
                fi


            ) &
        done
        ;;
    # Git diff all repositories
    d|diff)
        for d in ${base}/*; do
            cd ${d}
            git diff
        done
        ;;
    # Install/symlink all repositories to ~
    install)
        install_repositories
        ;;
    # Push all repositories
    push)
        for d in ${base}/*; do
            (
                cd ${d}
                remote=$(git config --local --get remote.origin.url) && \
                    echo "PUSH $remote" && \
                    git push -q origin master && \
                    echo "DONE $remote" && \
                    remote=$(git config --local --get remote.publish.url) && \
                    echo "PUSH $remote" && \
                    git push -q publish master && \
                    echo "DONE $remote"
            ) &
        done
        ;;
    # Pull all repositores
    pull)
        for d in ${base}/*; do
            cd ${d}
            git pull origin master
            install_repositories
        done
        ;;
    # Git status of all repositories
    s|status)
        for d in ${base}/*; do
            cd ${d}
            if [[ ! $(git status --porcelain) = "" ]]; then
                echo "##### $(basename ${d}) ######"
                git status --short
            fi
        done
        ;;
    # Run tig on all unclean repositories
    tig)
    for d in ${base}/*; do
        cd ${d}
        [[ ! $(git status --porcelain) = "" ]] && tig status
    done
    ;;
    # Run magit-status on all unclean repositories
    magit)
        el=""
        for d in ${base}/*; do
            cd ${d}
            [[ ! $(git status --porcelain) = "" ]] && el="${el} (magit-status \"${d}\")"
        done
        emacs -eval "(progn() ${el} )"
        ;;
    *)
        echo "Invalid argument!"
        exit 1
        ;;
esac
