#!/bin/sh

# Copyright (C) 2011 Peter J Weisberg.
#
# Magit is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# Magit is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public
# License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Magit.  If not, see <http://www.gnu.org/licenses/>.
# ====================================================================

if test "$1" = "-h" || test "$1" = "--help"; then
  cat <<EOF
Usage: magit [OPTION] [REPOSITORY] [REPOSITORY2]...

Open a Magit session in Emacs visiting the specified repository.  If no
repository is specified, and the current directory is a Git repository, use the
current directory.  Otherwise, magit-status will prompt for a repository to use.

    -h, --help          Print this text and exit
    -e, --use-existing  Use an existing Emacs frame instead of creating a new
                        one.  Requires that Emacs be running in server mode with
                        at least one visible frame.

If Emacs is running in server mode or if the ALTERNATE_EDITOR environment
variable is the empty string, emacsclient will be used.  Otherwise a new Emacs
session will be started.
EOF
  exit 0;
fi

# Disable any ALTERNATE_EDITOR except the special blank value.
[ -z "$ALTERNATE_EDITOR" ] || ALTERNATE_EDITOR=false


runmagit="(progn "
if [ -n "$1" ]; then
  for dir in $*; do
    runmagit="$runmagit (magit-status \"$(readlink -m ${dir})\")"
  done
else
  runmagit="$runmagit (let ((default-directory \"$(pwd)\"))
                          (call-interactively 'magit-status))"
fi

runmagit="$runmagit (delete-other-windows)"

runmagit="$runmagit nil)"

xsupport=false
if emacs -Q --batch --eval "(kill-emacs (if (featurep 'x) 0 1))"; then
  xsupport=true
fi

emacs --eval "$runmagit"

